name: Auto Tag and Release
on:
  push:
    paths:
      - 'plugin.yml'  # plugin.yml이 변경되었을 때만 트리거

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      version: ${{ steps.check-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check version
        id: check-version
        run: |
          # 현재 버전 가져오기
          CURRENT_VERSION=$(grep -oP 'version:\s*\K[0-9.]+' plugin.yml)
          echo "Current version: $CURRENT_VERSION"
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          VERSION=${{ steps.check-version.outputs.version }}
          echo "Creating new tag v$VERSION"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag "v$VERSION"
          git push origin "v$VERSION"

  release-latest:
    needs: check-version
    runs-on: ubuntu-latest
    permissions: write-all
    concurrency:
      group: release-latest
      cancel-in-progress: true
    env:
      RELEASE_DIR: "."
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: 'v${{ needs.check-version.outputs.version }}'  # 새로 생성된 태그로 체크아웃

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Download PresentKim/pmmp-plugin-build.php
        run: wget -O .github/workflows/pmmp-plugin-build.php https://raw.githubusercontent.com/PresentKim/scripts-for-action/main/pmmp-plugin-build.php

      - name: Build plugin with virion infecting
        run: php -dphar.readonly=0 .github/workflows/pmmp-plugin-build.php ${{ env.RELEASE_DIR }}

      - name: Find phar file and save path
        run: |
          PHAR_FILE=$(find .releases -name "*.phar" | head -n 1)
          if [ -z "$PHAR_FILE" ]; then
            echo "No .phar file found in .releases directory"
            exit 1
          fi
          echo "PHAR_FILE=$PHAR_FILE" >> $GITHUB_ENV
          echo "Found PHAR file: $PHAR_FILE"
          echo "PHAR_FILENAME=$(basename $PHAR_FILE)" >> $GITHUB_ENV
          
          # 파일 정보 확인
          ls -la "$PHAR_FILE"
          file "$PHAR_FILE"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: 'v${{ needs.check-version.outputs.version }}'
          artifacts: ".releases/*.phar"
          allowUpdates: true

  execute-server-command:
    needs: [ check-version, release-latest ]
    runs-on: ubuntu-latest
    steps:
      - name: Execute update command on Pterodactyl server
        run: |
          # GitHub 저장소 이름 가져오기
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)
          
          # 명령어 실행 요청
          COMMAND_RESULT=$(curl -s \
            "${{ secrets.PTERODACTYL_PANEL_URL }}/api/client/servers/${{ secrets.PTERODACTYL_SERVER_ID }}/command" \
            -H "Authorization: Bearer ${{ secrets.PTERODACTYL_API_KEY }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -X POST \
            -d "{\"command\":\"pu $REPO_NAME\"}")
          
          echo "Command execution result: $COMMAND_RESULT"
          
          # 명령어 실행 성공 여부 확인
          if [[ "$COMMAND_RESULT" == *"\"errors\":"* || "$COMMAND_RESULT" == *"\"error\":"* ]]; then
            echo "Failed to execute command on server."
            echo "Error details: $COMMAND_RESULT"
            exit 1
          else
            echo "Command 'pu $REPO_NAME' has been successfully executed on the server."
          fi

      - name: Send deployment notification
        run: |
          echo "Plugin version ${{ needs.check-version.outputs.version }} has been released and update command 'pu $REPO_NAME' has been executed on the server" >> $GITHUB_STEP_SUMMARY